Repository Spring-Study-KCM/Pay, pull requests merged in 2025-05, with the labels that each got.

#4 [REFACTOR] 친구 추가 삭제
  src/main/java/org/example/pay/user/controller/UserController.java
  src/main/java/org/example/pay/user/dto/request/AddFriendRequest.java
  src/main/java/org/example/pay/user/dto/request/DeleteFriendRequest.java
Labels: refactor

#16 [DOCS] 2주차 진행 결과
  README.md
Labels: documentation

#19 [1week] erd, api 문서 완성
  README.md
  build.gradle
Labels: enhancement

#21 [FEAT] 2주차
  README.md
  src/main/java/org/example/pay/auth/controller/AuthController.java
  src/main/java/org/example/pay/auth/dto/CustomUserDetails.java
  src/main/java/org/example/pay/auth/dto/TempLoginDto.java
  src/main/java/org/example/pay/auth/service/AuthService.java
  src/main/java/org/example/pay/auth/service/CustomUserDetailsService.java
  src/main/java/org/example/pay/auth/service/SecurityContextService.java
  src/main/java/org/example/pay/common/config/SecurityConfig.java
  src/main/java/org/example/pay/common/config/SwaggerConfig.java
  src/main/java/org/example/pay/common/entity/BaseEntity.java
  src/main/java/org/example/pay/member/constants/Role.java
  src/main/java/org/example/pay/member/controller/MemberController.java
  src/main/java/org/example/pay/member/domain/Member.java
  src/main/java/org/example/pay/member/dto/JoinDto.java
  src/main/java/org/example/pay/member/repository/MemberRepository.java
  src/main/java/org/example/pay/member/service/MemberService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: enhancement

#28 [DOCS] 3주차 - 진행 결과
  README.md
Labels: documentation
